LojaWeb/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using LojaServicos.Servicos;
using LojaRepositorios.Entidades;
using LojaWeb.Models.Cliente;
using LojaServicos.Dtos.Clientes;

namespace LojaWeb.Controllers
{
    [Route("/cliente")]

    public class ClienteController : Controller
    {
        private readonly IClienteServico _clienteServico;

        public ClienteController(IClienteServico clienteServico)
        {
            _clienteServico = clienteServico;
        }

        [HttpGet]
        public IActionResult Index([FromQuery] string? pesquisa) // cliente?pesquisa=OQUEQUEROPESQUISAR
        {
            var dtos = _clienteServico.ObterTodos(pesquisa);

            var viewModel = ConstruirClienteIndexViewModel(dtos, pesquisa);

            return View(viewModel);
        }

        private ClienteIndexViewModel ConstruirClienteIndexViewModel(List<ClienteIndexDto> dtos, string? pesquisa)
        {
            return new ClienteIndexViewModel
            {
                Pesquisa = pesquisa,
                Clientes = ConstruirClienteViewModel(dtos)
            };
        }

        private List<ClienteViewModel> ConstruirClienteViewModel(List<ClienteIndexDto> dtos)
        {
            var viewModels = new List<ClienteViewModel>();
            foreach (var dto in dtos)
            {
                viewModels.Add(new ClienteViewModel
                {
                    Id = dto.Id,
                    Nome = dto.Nome,
                    Cpf = dto.Cpf,
                    Endereco = dto.Endereco
                });
            }
            return viewModels;
        }

        [Route("cadastrar")]
        [HttpGet]
        public IActionResult Cadastrar()
        {
            var viewModel = new ClienteCadastroViewModel();

            return View();
        }

        [Route("cadastrar")]
        [HttpPost]
        public IActionResult Cadastrar([FromForm] ClienteCadastroViewModel clienteCadastro)
        {
            // Faz a validação que está presente dentro do ClienteCadastroViewModel que foi gerada
            // ModelState > Values > ResultsView > Ver os erros que estão dando
            if (ModelState.IsValid == false)
            {
                return View("Cadastrar", clienteCadastro);
            }

            var clienteCadastrarDto = ConstruirClienteCadastrarDto(clienteCadastro);

            _clienteServico.Cadastrar(clienteCadastrarDto);

            return RedirectToAction("Index");
        }

        public ClienteCadastrarDto ConstruirClienteCadastrarDto(ClienteCadastroViewModel viewModel)
        {
            return new ClienteCadastrarDto
            {
                Nome = viewModel.Nome.Trim(),
                Cpf = viewModel.Cpf.Trim(),
                DataNascimento = viewModel.DataNascimento.GetValueOrDefault(),
                Estado = viewModel.Estado,
                Cidade = viewModel.Cidade,
                Bairro = viewModel.Bairro,
                Cep = viewModel.Cep,
                Logradouro = viewModel.Logradouro,
                Numero = viewModel.Numero,
                Complemento = viewModel.Complemento
            };
        }
    }
}

LojaWeb/Controllers/ProdutoController.cs
using LojaRepositorios.Entidades;
using LojaServicos.Servicos;
using Microsoft.AspNetCore.Mvc;

namespace LojaWeb.Controllers
{
    [Route("/produto")]
    // Define a rota para acessar

    public class ProdutoController : Controller
    {
        private readonly IProdutoServico _produtoServico;
        public ProdutoController(IProdutoServico produtoServico)
        {
            _produtoServico = produtoServico;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var produtos = _produtoServico.ObterTodos(string.Empty);
            ViewBag.Produtos = produtos;

            return View();
        }

        [Route("cadastrar")]
        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [Route("cadastrar")]
        [HttpPost]
        public IActionResult Cadastrar(
            [FromForm] string nome,
            [FromForm] decimal precoUnitario
        )
        {
            var produto = new Produto();
            produto.Nome = nome.Trim();
            produto.PrecoUnitario = precoUnitario;
            produto.Quantidade = 1;

            _produtoServico.Cadastrar(produto);

            return RedirectToAction("Index");
        }

        [Route("apagar")]
        [HttpGet]
        public IActionResult Apagar([FromQuery] int id)
        {
            _produtoServico.Apagar(id);

            return RedirectToAction("Index");
        }

        [Route("editar")]
        [HttpGet]
        public IActionResult Editar([FromQuery] int id)
        {
            var produto = _produtoServico.ObterPorId(id);

            ViewBag.Produto = produto;
            return View();
        }

        [Route("editar")]
        [HttpPost]
        public IActionResult Editar(
            [FromQuery] int id,
            [FromForm] string nome,
            [FromForm] decimal precoUnitario)
        {
            var produto = new Produto();
            produto.Id = id;
            produto.Nome = nome;
            produto.PrecoUnitario = precoUnitario;
            produto.Quantidade = 1;

            _produtoServico.Editar(produto);

            return RedirectToAction("Index");
        }
    }
}

LojaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LojaWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LojaWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LojaWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produto" asp-action="Index">Produto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LojaWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="/lib/fontawesome-free-6.4.0-web/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>